version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductsDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    ports:
      - "8080:80"
    networks:
      - appnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  appnet:
